In [2]:
import numpy

In [3]:
arreglo = numpy.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [4]:
import numpy as np

In [5]:
arreglo = np.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [6]:
np?

In [7]:
#Dimensionamiento de arreglos:
#una dimension de un arreglo es el nivel de profundidad del arreglo (anidamiento)
#Escalares de 0-D
arreglo = np.array(3)
print(arreglo)

3


In [8]:
# Numpy tiene un atributo_ ndim que regresa el numero de dimensiones
cero = np.array(17)
uno = np.array([1, 2, 3, 4, 5])
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(cero.ndim)
print(uno.ndim)
print(dos.ndim)
print(tres.ndim)

0
1
2
3


In [9]:
type(tres)

numpy.ndarray

In [10]:
#Otro atributo, sólo que este es cuando se crea el arreglo
arreglo = np.array([1, 2, 3], ndmin = 4)
print(arreglo)
print("Dim :", arreglo.ndim)

[[[[1 2 3]]]]
Dim : 4


In [11]:
#Elementos de un arreglo
arreglo = np.array([1, 2, 3])
print(arreglo[0])
print(arreglo[0] * arreglo[1])

1
2


In [12]:
#Ahora con dimensiones
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(dos[0,1]) #en la dim 1 el segundpo elemento
print(dos[1,2]) #en la dim 2 el tercer elemento
print(tres[1, 1, 2]) #en la dim 1 [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]
#Dim 1: [10, 11, 12], elemento 2 : 12

2
6
12


In [13]:
#Se incluye el limite inferior pero no el superior
arreglo = np.array([1, 2, 3])
print(arreglo[0:3])
print(arreglo[0:1])
print(arreglo[:2])
print(arreglo[-1:-2])
#Saltos o pasos en un arreglo
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arreglo[2:9:3])
print(arreglo[::2])
dos = np.array([[1, 2, 3], [4, 5, 6]])
print(dos[1, 1:3])
print(dos[0:2, 1])
print(dos[0:2, 1:3])

[1 2 3]
[1]
[1 2]
[]
[3 6 9]
[1 3 5 7 9]
[5 6]
[2 5]
[[2 3]
 [5 6]]


In [14]:
arreglo = np.array([1, 2, 3])
print(arreglo.dtype)
arreglo = np.array([2.5, 70.45, 100.0])
print(arreglo.dtype)

int32
float64


In [15]:
arreglo = np.array([1, 2, 3], dtype = "i4")
print(arreglo)
print(arreglo.dtype)

[1 2 3]
int32


In [16]:
#arreglo = np.array(["Hugo", 2, "Luis"], dtype = "i")

In [17]:
arreglo = np.array([2.5, 70.45, 100.0])
#crea una copia del arreglo y convierte el tipo de dato
nuevo = arreglo.astype("i") #o int
print(nuevo)
print(nuevo.dtype)
nnuevo = nuevo.astype(bool)
print(nnuevo)
print(nnuevo.dtype)

[  2  70 100]
int32
[ True  True  True]
bool


In [18]:
import numpy as np
#Copiar arreglos: copia arreglo original, no modifica
#los elementos del arreglo original
arreglo = np.array([1, 2, 3])
nuevo = arreglo.copy()
arreglo[0] = 10
nuevo[1] = 20
print(arreglo)
print(nuevo)

[10  2  3]
[ 1 20  3]


In [19]:
#Vista : copia el arreglo original y las modificaciones que se realicen
#modifican el arreglo original
arreglo = np.array([1, 2, 3])
nuevo = arreglo.view()
arreglo[0] = 10
nuevo[1] = 20
print(arreglo)
print(nuevo)

[10 20  3]
[10 20  3]


In [20]:
#Atributo: base.
arreglo = np.array([1, 2, 3])
copia = arreglo.copy() # None
vista = arreglo.view()

print(copia.base) #None tiene su propia información
print(vista.base)

None
[1 2 3]


In [21]:
#shape: regresa una tupla con el 
#numero de elementos en cada dimenssion
dos = np.array([[1, 2, 3], [4, 5, 6]])
print(dos.shape)

(2, 3)


In [22]:
cinco = np.array([1, 2, 3], ndmin = 2)
print(cinco)
print(cinco.shape)

[[1 2 3]]
(1, 3)


In [23]:
#reshape: convierte un arreglo de una dimension a otra dimension
#numero de arreglo, numero de lementos
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#dos arreglos, de 5 elemetos cada arreglo
nuevo = arreglo.reshape(2, 5)
print(nuevo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
nuevo = arreglo.reshape(2, 3, 2)
print(nuevo)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [25]:
#arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#nuevo = arreglo.reshape(2, 3)
#print(nuevo)

In [26]:
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nuevo = arreglo.reshape(2, 5, -1) #-1, Numpy calcula este numero
#sólo se puede utilizar en una dimensión
print(nuevo)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [27]:
#Convierte un arreglo multidimensional a una dimension
n = nuevo.reshape(-1)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
arreglo = np.array([1, 2, 3])
for i in arreglo:
    print(i)

1
2
3


In [29]:
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i in dos:
    print(i)

[1 2 3]
[4 5 6]


In [30]:
#dos dimensiones
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i in dos:
    for j in i:
        print(j)

1
2
3
4
5
6


In [31]:
tres = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in tres:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [32]:
#Iteraciones sencillas -> complejas
#nditer()
#iteracion sencilla
for i in np.nditer(tres):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
arreglo = np.array([1, 2, 3])
#No se cambia el tipo de dato
#Crea un buffer para realizar la accion que se solicita
for i in np.nditer(arreglo, flags=["buffered"], op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'


In [34]:
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i in np.nditer(dos[:, ::2]): #se salta un elemento en cada dimension
    print(i)

1
3
4
6


In [35]:
#ndenumerate: es un indice durante la iteracion
arreglo = np.array([1, 2, 3])
for i, j in np.ndenumerate(arreglo):
    print(i, j)

(0,) 1
(1,) 2
(2,) 3


In [37]:
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i, j in np.ndenumerate(dos):
    print(i, j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [38]:
#Concatenate()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#arreglo = np.array((a, b))
arreglo = np.concatenate((a, b))
print(arreglo)

[1 2 3 4 5 6]


In [39]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
arreglo = np.concatenate((a, b))
print(arreglo)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
#Stack(): concatena pero se le indica la manera con axis
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#arreglo = np.array((a, b))
arreglo = np.stack((a, b), axis = 1)
arregloH = np.hstack((a, b)) #renglones
arregloV = np.vstack((a, b)) #columnas
arregloD = np.dstack((a, b)) #altura(profundidad)
print(arreglo)
print(arregloH)
print(arregloV)
print(arregloD)

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [41]:
uno = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arreglo = np.array_split(uno, 3) #divide en 3 arreglos
a, b, c = np.array_split(uno, 3)
print("Arreglo: ", arreglo)
print("Arreglo 1 : ", arreglo[0])
print("Arreglo 2 : ", arreglo[1])
print("Arreglo 3 : ", arreglo[2])
print("Imprime a: ", a)
print("Imprime b: ", b)
print("Imprime c: ", c)

Arreglo:  [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
Arreglo 1 :  [1 2 3 4]
Arreglo 2 :  [5 6 7]
Arreglo 3 :  [ 8  9 10]
Imprime a:  [1 2 3 4]
Imprime b:  [5 6 7]
Imprime c:  [ 8  9 10]


In [44]:
uno = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#Busqueda en un arreglo, devuelve una tupla
print("Busqueda en uno : ", np.where(uno == 8))
print("Pares en uno : ", np.where(uno%2 == 0))

Busqueda en uno :  (array([7], dtype=int64),)
Pares en uno :  (array([1, 3, 5, 7, 9], dtype=int64),)


In [45]:
#ordenando
uno = np.array([10, 6, 2, 8, 1])
dos = np.array([[10, 6, 2], [8, 1, 9]])
print("Ordenando uno: ", np.sort(uno))
print("Ordenando dos: ", np.sort(dos))

Ordenando uno:  [ 1  2  6  8 10]
Ordenando dos:  [[ 2  6 10]
 [ 1  8  9]]


In [46]:
#Comparación a manera de filtrado
arreglo = np.array([1, 2, 3])
val = [False, True, False]
nuevo = arreglo[val]
print(nuevo)

[2]


In [47]:
arreglo = np.array([1, 2, 3])
val = []
for i in arreglo:
    if i > 2:
        val.append(True)
    else:
        val.append(False)
nuevo = arreglo[val]
print(val)
print(nuevo)

[False, False, True]
[3]


In [48]:
#otra manera de filtrar, más directa
arreglo = np.array([1, 2, 3])
val = arreglo > 2
nuevo = arreglo[val]
print(val)
print(nuevo)

[False False  True]
[3]


In [50]:
#Pseudoaleatorios
from numpy import random
alea = random.randint(100) #un numero entero entre 0-100
print("Aleatorio : ", alea)
alea = random.rand #un numero entre 0-1
print("Aleatorio rand(): ", alea)
alea = random.rand(3)
print("Aleatorio rand(3): ", alea)
alea = random.randint(100, size = 3)
print("Aleatorio : ", alea)

Aleatorio :  11
Aleatorio rand():  <built-in method rand of numpy.random.mtrand.RandomState object at 0x000001A3CC3E2740>
Aleatorio rand(3):  [0.51777742 0.50399955 0.80647752]
Aleatorio :  [36  7 49]
