In [1]:
import numpy

In [3]:
arreglo = numpy.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [4]:
import numpy as np

In [5]:
arreglo = np.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [11]:
np?

In [7]:
#Dimensionamiento de arreglos:
#una dimension de un arreglo es el nivel de profundidad del arreglo (anidamiento)
#Escalares de 0-D
arreglo = np.array(3)
print(arreglo)

3


In [9]:
# Numpy tiene un atributo_ ndim que regresa el numero de dimensiones
cero = np.array(17)
uno = np.array([1, 2, 3, 4, 5])
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(cero.ndim)
print(uno.ndim)
print(dos.ndim)
print(tres.ndim)

0
1
2
3


In [10]:
type(tres)

numpy.ndarray

In [12]:
#Otro atributo, sólo que este es cuando se crea el arreglo
arreglo = np.array([1, 2, 3], ndmin = 4)
print(arreglo)
print("Dim :", arreglo.ndim)

[[[[1 2 3]]]]
Dim : 4


In [13]:
#Elementos de un arreglo
arreglo = np.array([1, 2, 3])
print(arreglo[0])
print(arreglo[0] * arreglo[1])

1
2


In [16]:
#Ahora con dimensiones
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(dos[0,1]) #en la dim 1 el segundpo elemento
print(dos[1,2]) #en la dim 2 el tercer elemento
print(tres[1, 1, 2]) #en la dim 1 [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]
#Dim 1: [10, 11, 12], elemento 2 : 12

2
6
12
