In [1]:
import numpy

In [2]:
arreglo = numpy.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [3]:
import numpy as np

In [4]:
arreglo = np.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [5]:
np?

In [6]:
#Dimensionamiento de arreglos:
#una dimension de un arreglo es el nivel de profundidad del arreglo (anidamiento)
#Escalares de 0-D
arreglo = np.array(3)
print(arreglo)

3


In [7]:
# Numpy tiene un atributo_ ndim que regresa el numero de dimensiones
cero = np.array(17)
uno = np.array([1, 2, 3, 4, 5])
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(cero.ndim)
print(uno.ndim)
print(dos.ndim)
print(tres.ndim)

0
1
2
3


In [8]:
type(tres)

numpy.ndarray

In [9]:
#Otro atributo, sólo que este es cuando se crea el arreglo
arreglo = np.array([1, 2, 3], ndmin = 4)
print(arreglo)
print("Dim :", arreglo.ndim)

[[[[1 2 3]]]]
Dim : 4


In [10]:
#Elementos de un arreglo
arreglo = np.array([1, 2, 3])
print(arreglo[0])
print(arreglo[0] * arreglo[1])

1
2


In [11]:
#Ahora con dimensiones
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(dos[0,1]) #en la dim 1 el segundpo elemento
print(dos[1,2]) #en la dim 2 el tercer elemento
print(tres[1, 1, 2]) #en la dim 1 [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]
#Dim 1: [10, 11, 12], elemento 2 : 12

2
6
12


In [12]:
#Se incluye el limite inferior pero no el superior
arreglo = np.array([1, 2, 3])
print(arreglo[0:3])
print(arreglo[0:1])
print(arreglo[:2])
print(arreglo[-1:-2])
#Saltos o pasos en un arreglo
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arreglo[2:9:3])
print(arreglo[::2])
dos = np.array([[1, 2, 3], [4, 5, 6]])
print(dos[1, 1:3])
print(dos[0:2, 1])
print(dos[0:2, 1:3])

[1 2 3]
[1]
[1 2]
[]
[3 6 9]
[1 3 5 7 9]
[5 6]
[2 5]
[[2 3]
 [5 6]]


In [13]:
arreglo = np.array([1, 2, 3])
print(arreglo.dtype)
arreglo = np.array([2.5, 70.45, 100.0])
print(arreglo.dtype)

int32
float64


In [16]:
arreglo = np.array([1, 2, 3], dtype = "i4")
print(arreglo)
print(arreglo.dtype)

[1 2 3]
int32


In [17]:
#arreglo = np.array(["Hugo", 2, "Luis"], dtype = "i")

ValueError: invalid literal for int() with base 10: 'Hugo'

In [20]:
arreglo = np.array([2.5, 70.45, 100.0])
#crea una copia del arreglo y convierte el tipo de dato
nuevo = arreglo.astype("i") #o int
print(nuevo)
print(nuevo.dtype)
nnuevo = nuevo.astype(bool)
print(nnuevo)
print(nnuevo.dtype)

[  2  70 100]
int32
[ True  True  True]
bool


In [21]:
import numpy as np
#Copiar arreglos: copia arreglo original, no modifica
#los elementos del arreglo original
arreglo = np.array([1, 2, 3])
nuevo = arreglo.copy()
arreglo[0] = 10
nuevo[1] = 20
print(arreglo)
print(nuevo)

[10  2  3]
[ 1 20  3]


In [22]:
#Vista : copia el arreglo original y las modificaciones que se realicen
#modifican el arreglo original
arreglo = np.array([1, 2, 3])
nuevo = arreglo.view()
arreglo[0] = 10
nuevo[1] = 20
print(arreglo)
print(nuevo)

[10 20  3]
[10 20  3]


In [23]:
#Atributo: base.
arreglo = np.array([1, 2, 3])
copia = arreglo.copy() # None
vista = arreglo.view()

print(copia.base) #None tiene su propia información
print(vista.base)

None
[1 2 3]
