In [1]:
import numpy

In [2]:
arreglo = numpy.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [3]:
import numpy as np

In [4]:
arreglo = np.array([1, 2, 3])
print(arreglo)

[1 2 3]


In [5]:
np?

In [6]:
#Dimensionamiento de arreglos:
#una dimension de un arreglo es el nivel de profundidad del arreglo (anidamiento)
#Escalares de 0-D
arreglo = np.array(3)
print(arreglo)

3


In [7]:
# Numpy tiene un atributo_ ndim que regresa el numero de dimensiones
cero = np.array(17)
uno = np.array([1, 2, 3, 4, 5])
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(cero.ndim)
print(uno.ndim)
print(dos.ndim)
print(tres.ndim)

0
1
2
3


In [8]:
type(tres)

numpy.ndarray

In [9]:
#Otro atributo, sólo que este es cuando se crea el arreglo
arreglo = np.array([1, 2, 3], ndmin = 4)
print(arreglo)
print("Dim :", arreglo.ndim)

[[[[1 2 3]]]]
Dim : 4


In [10]:
#Elementos de un arreglo
arreglo = np.array([1, 2, 3])
print(arreglo[0])
print(arreglo[0] * arreglo[1])

1
2


In [11]:
#Ahora con dimensiones
dos = np.array([[1, 2, 3], [4, 5, 6]])
tres = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(dos[0,1]) #en la dim 1 el segundpo elemento
print(dos[1,2]) #en la dim 2 el tercer elemento
print(tres[1, 1, 2]) #en la dim 1 [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]
#Dim 1: [10, 11, 12], elemento 2 : 12

2
6
12


In [12]:
#Se incluye el limite inferior pero no el superior
arreglo = np.array([1, 2, 3])
print(arreglo[0:3])
print(arreglo[0:1])
print(arreglo[:2])
print(arreglo[-1:-2])
#Saltos o pasos en un arreglo
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arreglo[2:9:3])
print(arreglo[::2])
dos = np.array([[1, 2, 3], [4, 5, 6]])
print(dos[1, 1:3])
print(dos[0:2, 1])
print(dos[0:2, 1:3])

[1 2 3]
[1]
[1 2]
[]
[3 6 9]
[1 3 5 7 9]
[5 6]
[2 5]
[[2 3]
 [5 6]]


In [13]:
arreglo = np.array([1, 2, 3])
print(arreglo.dtype)
arreglo = np.array([2.5, 70.45, 100.0])
print(arreglo.dtype)

int32
float64


In [14]:
arreglo = np.array([1, 2, 3], dtype = "i4")
print(arreglo)
print(arreglo.dtype)

[1 2 3]
int32


In [15]:
#arreglo = np.array(["Hugo", 2, "Luis"], dtype = "i")

In [16]:
arreglo = np.array([2.5, 70.45, 100.0])
#crea una copia del arreglo y convierte el tipo de dato
nuevo = arreglo.astype("i") #o int
print(nuevo)
print(nuevo.dtype)
nnuevo = nuevo.astype(bool)
print(nnuevo)
print(nnuevo.dtype)

[  2  70 100]
int32
[ True  True  True]
bool


In [17]:
import numpy as np
#Copiar arreglos: copia arreglo original, no modifica
#los elementos del arreglo original
arreglo = np.array([1, 2, 3])
nuevo = arreglo.copy()
arreglo[0] = 10
nuevo[1] = 20
print(arreglo)
print(nuevo)

[10  2  3]
[ 1 20  3]


In [18]:
#Vista : copia el arreglo original y las modificaciones que se realicen
#modifican el arreglo original
arreglo = np.array([1, 2, 3])
nuevo = arreglo.view()
arreglo[0] = 10
nuevo[1] = 20
print(arreglo)
print(nuevo)

[10 20  3]
[10 20  3]


In [19]:
#Atributo: base.
arreglo = np.array([1, 2, 3])
copia = arreglo.copy() # None
vista = arreglo.view()

print(copia.base) #None tiene su propia información
print(vista.base)

None
[1 2 3]


In [21]:
#shape: regresa una tupla con el 
#numero de elementos en cada dimenssion
dos = np.array([[1, 2, 3], [4, 5, 6]])
print(dos.shape)

(2, 3)


In [23]:
cinco = np.array([1, 2, 3], ndmin = 2)
print(cinco)
print(cinco.shape)

[[1 2 3]]
(1, 3)


In [24]:
#reshape: convierte un arreglo de una dimension a otra dimension
#numero de arreglo, numero de lementos
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#dos arreglos, de 5 elemetos cada arreglo
nuevo = arreglo.reshape(2, 5)
print(nuevo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
nuevo = arreglo.reshape(2, 3, 2)
print(nuevo)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
#arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#nuevo = arreglo.reshape(2, 3)
#print(nuevo)

ValueError: cannot reshape array of size 10 into shape (2,3)

In [30]:
arreglo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nuevo = arreglo.reshape(2, 5, -1) #-1, Numpy calcula este numero
#sólo se puede utilizar en una dimensión
print(nuevo)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [31]:
#Convierte un arreglo multidimensional a una dimension
n = nuevo.reshape(-1)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
arreglo = np.array([1, 2, 3])
for i in arreglo:
    print(i)

1
2
3


In [34]:
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i in dos:
    print(i)

[1 2 3]
[4 5 6]


In [35]:
#dos dimensiones
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i in dos:
    for j in i:
        print(j)

1
2
3
4
5
6


In [36]:
tres = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in tres:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [37]:
#Iteraciones sencillas -> complejas
#nditer()
#iteracion sencilla
for i in np.nditer(tres):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [38]:
arreglo = np.array([1, 2, 3])
#No se cambia el tipo de dato
#Crea un buffer para realizar la accion que se solicita
for i in np.nditer(arreglo, flags=["buffered"], op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'


In [39]:
dos = np.array([[1, 2, 3], [4, 5, 6]])
for i in np.nditer(dos[:, ::2]): #se salta un elemento en cada dimension
    print(i)

1
3
4
6


In [40]:
#ndenumerate: es un indice durante la iteracion
arreglo = np.array([1, 2, 3])
for i, j in np.ndenumerate(arreglo):
    print(i, j)

(0,) 1
(1,) 2
(2,) 3
